// Mocks generated by Mockito 5.4.4 from annotations
// in salam/test/data/repositories/community_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:salam/data/datasources/community_remote_datasource.dart' as _i4;
import 'package:salam/data/models/comment_model.dart' as _i3;
import 'package:salam/data/models/post_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostModel_0 extends _i1.SmartFake implements _i2.PostModel {
  _FakePostModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentModel_1 extends _i1.SmartFake implements _i3.CommentModel {
  _FakeCommentModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommunityRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRemoteDataSource extends _i1.Mock
    implements _i4.CommunityRemoteDataSource {
  MockCommunityRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.PostModel>> getPosts({
    int? limit = 20,
    String? lastPostId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
          {
            #limit: limit,
            #lastPostId: lastPostId,
          },
        ),
        returnValue: _i5.Future<List<_i2.PostModel>>.value(<_i2.PostModel>[]),
      ) as _i5.Future<List<_i2.PostModel>>);

  @override
  _i5.Future<_i2.PostModel> getPost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #getPost,
          [postId],
        ),
        returnValue: _i5.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #getPost,
            [postId],
          ),
        )),
      ) as _i5.Future<_i2.PostModel>);

  @override
  _i5.Future<List<_i2.PostModel>> getPostsByVerse({
    required int? surahNumber,
    required int? verseNumber,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsByVerse,
          [],
          {
            #surahNumber: surahNumber,
            #verseNumber: verseNumber,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i2.PostModel>>.value(<_i2.PostModel>[]),
      ) as _i5.Future<List<_i2.PostModel>>);

  @override
  _i5.Future<_i2.PostModel> createPost({
    required String? userId,
    required String? userName,
    required String? content,
    int? surahNumber,
    int? verseNumber,
    String? verseText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [],
          {
            #userId: userId,
            #userName: userName,
            #content: content,
            #surahNumber: surahNumber,
            #verseNumber: verseNumber,
            #verseText: verseText,
          },
        ),
        returnValue: _i5.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #createPost,
            [],
            {
              #userId: userId,
              #userName: userName,
              #content: content,
              #surahNumber: surahNumber,
              #verseNumber: verseNumber,
              #verseText: verseText,
            },
          ),
        )),
      ) as _i5.Future<_i2.PostModel>);

  @override
  _i5.Future<_i2.PostModel> updatePost({
    required String? postId,
    required String? userId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [],
          {
            #postId: postId,
            #userId: userId,
            #content: content,
          },
        ),
        returnValue: _i5.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #updatePost,
            [],
            {
              #postId: postId,
              #userId: userId,
              #content: content,
            },
          ),
        )),
      ) as _i5.Future<_i2.PostModel>);

  @override
  _i5.Future<void> deletePost(
    String? postId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [
            postId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.PostModel> toggleLikePost({
    required String? postId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLikePost,
          [],
          {
            #postId: postId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #toggleLikePost,
            [],
            {
              #postId: postId,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<_i2.PostModel>);

  @override
  _i5.Future<void> reportPost({
    required String? postId,
    required String? userId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportPost,
          [],
          {
            #postId: postId,
            #userId: userId,
            #reason: reason,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.CommentModel>> getComments({
    required String? postId,
    int? limit = 50,
    String? lastCommentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [],
          {
            #postId: postId,
            #limit: limit,
            #lastCommentId: lastCommentId,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.CommentModel>>.value(<_i3.CommentModel>[]),
      ) as _i5.Future<List<_i3.CommentModel>>);

  @override
  _i5.Future<_i3.CommentModel> createComment({
    required String? postId,
    required String? userId,
    required String? userName,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [],
          {
            #postId: postId,
            #userId: userId,
            #userName: userName,
            #content: content,
          },
        ),
        returnValue: _i5.Future<_i3.CommentModel>.value(_FakeCommentModel_1(
          this,
          Invocation.method(
            #createComment,
            [],
            {
              #postId: postId,
              #userId: userId,
              #userName: userName,
              #content: content,
            },
          ),
        )),
      ) as _i5.Future<_i3.CommentModel>);

  @override
  _i5.Future<_i3.CommentModel> updateComment({
    required String? commentId,
    required String? userId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateComment,
          [],
          {
            #commentId: commentId,
            #userId: userId,
            #content: content,
          },
        ),
        returnValue: _i5.Future<_i3.CommentModel>.value(_FakeCommentModel_1(
          this,
          Invocation.method(
            #updateComment,
            [],
            {
              #commentId: commentId,
              #userId: userId,
              #content: content,
            },
          ),
        )),
      ) as _i5.Future<_i3.CommentModel>);

  @override
  _i5.Future<void> deleteComment(
    String? commentId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [
            commentId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.CommentModel> toggleLikeComment({
    required String? commentId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLikeComment,
          [],
          {
            #commentId: commentId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<_i3.CommentModel>.value(_FakeCommentModel_1(
          this,
          Invocation.method(
            #toggleLikeComment,
            [],
            {
              #commentId: commentId,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<_i3.CommentModel>);

  @override
  _i5.Future<void> reportComment({
    required String? commentId,
    required String? userId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportComment,
          [],
          {
            #commentId: commentId,
            #userId: userId,
            #reason: reason,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.PostModel>> getUserPosts({
    required String? userId,
    int? limit = 20,
    String? lastPostId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPosts,
          [],
          {
            #userId: userId,
            #limit: limit,
            #lastPostId: lastPostId,
          },
        ),
        returnValue: _i5.Future<List<_i2.PostModel>>.value(<_i2.PostModel>[]),
      ) as _i5.Future<List<_i2.PostModel>>);

  @override
  _i5.Future<List<_i2.PostModel>> getUserLikedPosts({
    required String? userId,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLikedPosts,
          [],
          {
            #userId: userId,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i2.PostModel>>.value(<_i2.PostModel>[]),
      ) as _i5.Future<List<_i2.PostModel>>);
}
