// Mocks generated by Mockito 5.4.4 from annotations
// in salam/test/presentation/providers/community_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:salam/core/utils/result.dart' as _i5;
import 'package:salam/domain/entities/comment_entity.dart' as _i11;
import 'package:salam/domain/entities/post_entity.dart' as _i6;
import 'package:salam/domain/repositories/community_repository_interface.dart'
    as _i2;
import 'package:salam/domain/usecases/community/create_comment_usecase.dart'
    as _i10;
import 'package:salam/domain/usecases/community/create_post_usecase.dart'
    as _i8;
import 'package:salam/domain/usecases/community/get_comments_usecase.dart'
    as _i12;
import 'package:salam/domain/usecases/community/get_posts_usecase.dart' as _i3;
import 'package:salam/domain/usecases/community/toggle_like_post_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommunityRepositoryInterface_0 extends _i1.SmartFake
    implements _i2.CommunityRepositoryInterface {
  _FakeCommunityRepositoryInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPostsUseCase extends _i1.Mock implements _i3.GetPostsUseCase {
  MockGetPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommunityRepositoryInterface get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCommunityRepositoryInterface_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CommunityRepositoryInterface);

  @override
  _i4.Future<_i5.Result<List<_i6.PostEntity>>> execute({
    int? limit = 20,
    String? lastPostId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #limit: limit,
            #lastPostId: lastPostId,
          },
        ),
        returnValue: _i4.Future<_i5.Result<List<_i6.PostEntity>>>.value(
            _i7.dummyValue<_i5.Result<List<_i6.PostEntity>>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #limit: limit,
              #lastPostId: lastPostId,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<List<_i6.PostEntity>>>);
}

/// A class which mocks [CreatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreatePostUseCase extends _i1.Mock implements _i8.CreatePostUseCase {
  MockCreatePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommunityRepositoryInterface get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCommunityRepositoryInterface_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CommunityRepositoryInterface);

  @override
  _i4.Future<_i5.Result<_i6.PostEntity>> execute({
    required String? userId,
    required String? userName,
    required String? content,
    int? surahNumber,
    int? verseNumber,
    String? verseText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #userId: userId,
            #userName: userName,
            #content: content,
            #surahNumber: surahNumber,
            #verseNumber: verseNumber,
            #verseText: verseText,
          },
        ),
        returnValue: _i4.Future<_i5.Result<_i6.PostEntity>>.value(
            _i7.dummyValue<_i5.Result<_i6.PostEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #userId: userId,
              #userName: userName,
              #content: content,
              #surahNumber: surahNumber,
              #verseNumber: verseNumber,
              #verseText: verseText,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.PostEntity>>);
}

/// A class which mocks [ToggleLikePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleLikePostUseCase extends _i1.Mock
    implements _i9.ToggleLikePostUseCase {
  MockToggleLikePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommunityRepositoryInterface get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCommunityRepositoryInterface_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CommunityRepositoryInterface);

  @override
  _i4.Future<_i5.Result<void>> execute({
    required String? postId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #postId: postId,
            #userId: userId,
          },
        ),
        returnValue:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #postId: postId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [CreateCommentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCommentUseCase extends _i1.Mock
    implements _i10.CreateCommentUseCase {
  MockCreateCommentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommunityRepositoryInterface get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCommunityRepositoryInterface_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CommunityRepositoryInterface);

  @override
  _i4.Future<_i5.Result<_i11.CommentEntity>> execute({
    required String? postId,
    required String? userId,
    required String? userName,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #postId: postId,
            #userId: userId,
            #userName: userName,
            #content: content,
          },
        ),
        returnValue: _i4.Future<_i5.Result<_i11.CommentEntity>>.value(
            _i7.dummyValue<_i5.Result<_i11.CommentEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #postId: postId,
              #userId: userId,
              #userName: userName,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<_i11.CommentEntity>>);
}

/// A class which mocks [GetCommentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCommentsUseCase extends _i1.Mock
    implements _i12.GetCommentsUseCase {
  MockGetCommentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommunityRepositoryInterface get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCommunityRepositoryInterface_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CommunityRepositoryInterface);

  @override
  _i4.Future<_i5.Result<List<_i11.CommentEntity>>> execute({
    required String? postId,
    int? limit = 50,
    String? lastCommentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #postId: postId,
            #limit: limit,
            #lastCommentId: lastCommentId,
          },
        ),
        returnValue: _i4.Future<_i5.Result<List<_i11.CommentEntity>>>.value(
            _i7.dummyValue<_i5.Result<List<_i11.CommentEntity>>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #postId: postId,
              #limit: limit,
              #lastCommentId: lastCommentId,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<List<_i11.CommentEntity>>>);
}
