// Mocks generated by Mockito 5.4.4 from annotations
// in salam/test/presentation/providers/islamic_calendar_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:hijri/hijri_calendar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:salam/domain/entities/islamic_event_entity.dart' as _i5;
import 'package:salam/domain/usecases/get_hijri_date_usecase.dart' as _i3;
import 'package:salam/domain/usecases/get_islamic_events_usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHijriCalendar_0 extends _i1.SmartFake implements _i2.HijriCalendar {
  _FakeHijriCalendar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetHijriDateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHijriDateUseCase extends _i1.Mock
    implements _i3.GetHijriDateUseCase {
  MockGetHijriDateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HijriCalendar execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _FakeHijriCalendar_0(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        ),
      ) as _i2.HijriCalendar);
}

/// A class which mocks [GetIslamicEventsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetIslamicEventsUseCase extends _i1.Mock
    implements _i4.GetIslamicEventsUseCase {
  MockGetIslamicEventsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.IslamicEventEntity> execute(int? hijriMonth) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [hijriMonth],
        ),
        returnValue: <_i5.IslamicEventEntity>[],
      ) as List<_i5.IslamicEventEntity>);
}
